spring.application.name=academia

# Configurações do MySQL (O banco 'academia' foi criado pelo docker-compose)
spring.datasource.url=jdbc:mysql://localhost:3306/academia?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# Hibernate continua funcionando igual, o JPA cuida da diferença
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# O console do H2 não será mais necessário, usará o IntelliJ ou DBeaver