spring.application.name=academia
spring.datasource.url=jdbc:mysql://localhost:3306/academiaapi

# Se o Spring não achar a variável DB_USER, ele usa 'root' automaticamente
spring.datasource.username=${DB_USER:root}

# Se o Spring não achar a variável DB_PASSWORD, ele usa '1234' automaticamente
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true